### ISSUE TITLE
Unable to resolve bare specifier "@/root-config"

### ISSUE THREAD

**Issue by dima19972525** [single-spa/create-single-spa#102]
Hi.
Yesterday:
i've created a root-config project using npm init single-spa command. After project was created i ran it with npm start and everythins was good.

Today:
Exactly same steps (create project using npm init.. npm start)
and i get this error.
![image](https://user-images.githubusercontent.com/23092460/79989173-3b2ee780-84b8-11ea-8b37-b6a0de8b3d9e.png)

Could you help me please with this?
Thank you in advance.

**Comment by dima19972525** [comment]
@joeldenniing thank you so much. It helped.

**Comment by evanjmg** [comment]
Followed the instructions getting the same issue with latest on this blog using typescript react following these instructions https://single-spa.js.org/docs/getting-started-overview and these https://medium.com/litslink/how-to-create-react-micro-frontends-from-scratch-using-single-spa-framework-in-examples-592c7f63bedf
