### ISSUE TITLE
Image relative paths not working in default Vue project

### ISSUE THREAD

**Issue by RyanEdwardHall** [single-spa/create-single-spa#105]
When I use create-single-spa to create the default vue project, the vue logo is generated with the wrong path. App.vue has `<img alt="Vue logo" src="./assets/logo.png" />` in the template, but when i view the application inside a single-spa container, the image is broken, and the image src is incorrectly generated as: `localhost:8081/js/img/logo-{hash}.png`. Removing /js/ fixes it, but it's not clear how to modify the project to prevent that from happening. Thanks for any help!

**Comment by RyanEdwardHall** [comment]
I found this, which seems to be the answer: https://github.com/joeldenning/systemjs-webpack-interop#what-is-this

**Comment by joeldenning** [comment]
Hi @RyanEdwardHall - yes the webpack public path needs to be configured in order for this to work. vue-cli-plugin-single-spa automatically does this ([code](https://github.com/single-spa/vue-cli-plugin-single-spa/blob/master/template/src/set-public-path.js)).

Was that not set up automatically for you when you used create-single-spa? The Vue project generated by create-single-spa should already have the webpack public path set up.
