### ISSUE TITLE
Automatically install single-spa for angular apps

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#106]
As of single-spa-angular@4, single-spa is now a peerDependency of single-spa-angular. As such, we should update the ng-add command to also install single-spa

**Comment by filoxo** [comment]
Should this be done in the angular schematic instead? I dove into this a little bit and I think it should be added to this file: https://github.com/single-spa/single-spa-angular/blob/ff2acca6fc66c12ad876d1dc883f45748822becf/schematics/ng-add/dependencies.ts

**Comment by filoxo** [comment]
This should be resolved as of [single-spa-angular@4.1.0-alpha.0](https://github.com/single-spa/single-spa-angular/releases/tag/v4.1.0-alpha.0).
