### ISSUE TITLE
Request to add dependencies in release

### ISSUE THREAD

**Issue by majoshi1** [single-spa/create-single-spa#111]
The usual install does not work due to corporate firewall.

npm install create-single-spa
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN tarball tarball data for generator-single-spa@^1.7.3 (sha1-RO0LGf86th088Ir77vKk5etOQ8o=) seems to be corrupted. Trying one more time.
[            ......] / extract:rxjs: WARN tarball tarball data for generator-single-spa@^1.7.3 (sha1-RO0LGf86th088Ir77v

Workaround: Pulled latest release.
https://github.com/single-spa/create-single-spa/releases

Run following steps:
npm install yeoman-environment
npm install packages/generator-single-spa

The package.json got following lines:
  "dependencies": {
    "generator-single-spa": "file:packages/generator-single-spa",
    "yeoman-environment": "^2.10.0"
  }

**Comment by joeldenning** [comment]
Hi @majoshi1 - this github repository is a [lerna monorepo](https://github.com/lerna/lerna) which intentionally does not have runnable scripts in the root package.json. To run the source code you should follow the instructions in [CONTRIBUTING.md](https://github.com/single-spa/create-single-spa/blob/master/CONTRIBUTING.md#running-the-create-single-spa-cli), which include running `lerna bootstrap`.

**Comment by majoshi1** [comment]
I am not trying to run the source code. I am just trying to use the CLI. Updated description to clarify.

**Comment by joeldenning** [comment]
By downloading the release, you are running the source code. There's no compilation step for this project - it's just javascript run by nodejs. Please follow the instructions I linked to above, which explain how to run the project locally
