### ISSUE TITLE
Unable to resolve bare specifier 'single-spa'

### ISSUE THREAD

**Issue by tangkunyin** [single-spa/create-single-spa#122]
Hi there.
I've created a root-config project using create-single-spa command. After project created I ran it with npm start and an error occured
![image](https://user-images.githubusercontent.com/4197468/82399427-b2d83e00-9a87-11ea-8d77-382efdd8f1ef.png)

Then I look at the roo-config in https://github.com/react-microfrontends/root-config/blob/master/src/index.ejs where I found the script tag like this

![image](https://user-images.githubusercontent.com/4197468/82399943-c932c980-9a88-11ea-873f-af69316923bf.png)

The problem for me is that is it a bug for create-single-spa built-in template index.ejs ?

`single-spa` also exists as one of dependencies in package.json, is it useless?

Thanks for your supporting in advance!

**Comment by tangkunyin** [comment]
I tried to new a local importmap file and add to index.ejs
![image](https://user-images.githubusercontent.com/4197468/82419658-496d2500-9ab1-11ea-92e2-5f867c85b939.png)

```json
{
    "imports": {
        "single-spa": "https://cdnjs.cloudflare.com/ajax/libs/single-spa/5.5.1/umd/single-spa.min.js",
        "react": "https://cdnjs.cloudflare.com/ajax/libs/react/16.13.1/umd/react.production.min.js",
        "react-dom": "https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.13.1/umd/react-dom.production.min.js"
    }
}
```

Then all errors disappeared. Does this mean that in the new roo-config project, developers must manually create their own importmap file instead of relying only on the template's own configuration?

**Comment by filoxo** [comment]
Correct. You must add to the importmap as you add new shared dependencies. https://single-spa.js.org/docs/recommended-setup/#sharing-with-import-maps

create-single-spa already includes single-spa in the generated root-config. So somehow that got removed or was created before that line was added. https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/root-config/templates/src/index.ejs#L32

And since you created a React application, you added react and react-dom correctly. We are exploring ways of reducing this friction and helping beginners learn how it all works together.

**Comment by joeldenning** [comment]
Carlos is completely correct - one thing I'd like to ask is which version of create-single-spa are you using? If you're using create-single-spa@>=1.8.0 you should not see the bare specifier error for single-spa anymore. If you're using >=1.8.0 and still seeing the error, that would be a thing for us to fix.

**Comment by filoxo** [comment]
I tested this with create-single-spa running locally as well as with what's currently available with `npx create-single-spa` and was not able to replicate the problem.

**Comment by joeldenning** [comment]
Cool let's close this then, since there doesn't appear to be an issue with the latest versions of create-single-spa. Feel free @tangkunyin  to comment further or reopen.

**Comment by tangkunyin** [comment]
@filoxo @joeldenning Many thanks!!!

**Comment by nourhan-maxab** [comment]
i have the same problem right now, can anyone help me ?
