### ISSUE TITLE
Create-single-spa of svelte from cli

### ISSUE THREAD

**Issue by limitall** [single-spa/create-single-spa#123]
Please provide steps or add svelte as a option in cli

**Comment by joeldenning** [comment]
Hi @limitall - sure let's keep this issue open to track it. The single spa core team might get to this at some point, and would also welcome outside contribution on it. All others interested in this, please show support with a thumbs up emoji on the original issue.

**Comment by tangkunyin** [comment]
@limitall The cli did't provide svelte template until version 1.9.0.But you can refer this: https://single-spa.js.org/docs/ecosystem-svelte

Refer to my operation below：

1. create a svelte app
```
npx degit sveltejs/template svelte-app
```

2. create index.js like this
```
import singleSpaSvelte from "single-spa-svelte";
import SvelteApp from "./main";

const svelteLifecycles = singleSpaSvelte({
  component: function () {
    return SvelteApp;
  },
  domElementGetter: () => document.getElementById("svelte-app"),
  props: {},
});

export const bootstrap = svelteLifecycles.bootstrap;
export const mount = svelteLifecycles.mount;
export const unmount = svelteLifecycles.unmount;
```

3. registe application in root-config
```
registerApplication({
  name: "svelte-app",
  app: () => System.import("@your-org/svelte-app"),
  activeWhen: isActive.svelte,
});
```

4. import map

```
<script type="systemjs-importmap">
    {
      "imports": {
        "@your-og/svelte-app": "//localhost:9003/build/bundle.js"
      }
    }
  </script>
```

**Comment by filoxo** [comment]
Generating a Svelte application was added to [create-single-spa@1.10.0](https://github.com/single-spa/create-single-spa/releases/tag/v1.10.0).
