### ISSUE TITLE
Rename .babelrc to babel.config.json

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#130]
See https://babeljs.io/docs/en/config-files - in babel 7 they're now encouraging using `babel.config.json`, which we should switch to.

**Comment by zanza00** [comment]
@joeldenning I would like to tackle this issue if possible.

**Comment by joeldenning** [comment]
👍 yes please do!

**Comment by filoxo** [comment]
This was resolved in https://github.com/single-spa/create-single-spa/pull/133 but for some reason it didn't link to this issue to close it once the PR merged. Closing now.
