### ISSUE TITLE
Add a notification banner for outdated version of create-single-spa

### ISSUE THREAD

**Issue by filoxo** [single-spa/create-single-spa#142]
Feature request: 
I was helping someone recently with a create-single-spa question and I made the mistake of assuming they had the latest version (see https://single-spa.slack.com/archives/C8R6U7MT7/p1592326497247200?thread_ts=1592320975.228600&cid=C8R6U7MT7). If someone instead installed via `npm i -g create-single-spa` then it would get out of date after some time.
I think it would be great to show a notification if the user is not using the latest version of create-single-spa and prompt them to update. Other projects such as yarn display something like this which I think is helpful. Here is an example from another package I have globally installed:

<img width="526" alt="Screen Shot 2020-06-19 at 10 56 33 AM" src="https://user-images.githubusercontent.com/4202993/85160048-97458c00-b21b-11ea-9b6a-f9af12d6196d.png">

I can get to this eventually but this would be a great first feature if someone would like to contribute. Feel free to comment if you're interested in taking this on, and we would be happy to help/answer any questions.

**Comment by joeldenning** [comment]
I agree this would be a nice feature to have. We could perhaps use https://www.npmjs.com/package/latest-version to help implement it.

**Comment by filoxo** [comment]
If we don't want to add another dependency, I was thinking that the implementation could just use yeoman's [`spawnCommand`](https://yeoman.io/authoring/dependencies.html#using-other-tools) and npm's built-in [`view`](https://docs.npmjs.com/cli-commands/view.html) (eg. `npm view create-single-spa@latest version`) to get the latest create-single-spa version to compare to.
