### ISSUE TITLE
Vue apps do not prompt for organization name

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#148]
When you use create-single-spa to generate a vue app, you are not prompted for the organization name, which is added as a prefix `@org/`. See https://github.com/single-spa/vue-cli-plugin-single-spa/blob/8b7076be0b8cb45c6596a5a6ac283c65e6929834/template/src/set-public-path.js#L3 and https://github.com/single-spa/vue-cli-plugin-single-spa/blob/58caee10211696d2c7a8780d6eb6c21a46c2fd49/generator.js#L3.

The `appName` variable is coming from the package.json of the generated vue cli project. The package.json name comes from the argument passed to `vue create <dir name>`. More documentation about this at https://cli.vuejs.org/guide/creating-a-project.html#vue-create.

cc @mattjonesorg and @tylerkeesling who were there when we discovered this.

Here are proposed changes:

1. Add the organization and project name prompts to create-single-spa, similar to how most of the generators do it. [Example](https://github.com/single-spa/create-single-spa/blob/74a99b37c0ea3229216a82332faa0f34086c0bfb/packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js#L54-L84)
2. Research if it's possible to pass in a name with `/` in it to Vue CLI without it creating a directory for that slash. If so, invoke Vue CLI in that way. [Code to change](https://github.com/single-spa/create-single-spa/blob/74a99b37c0ea3229216a82332faa0f34086c0bfb/packages/generator-single-spa/src/vue/generator-single-spa-vue.js#L29)

**Comment by filoxo** [comment]
For 2, I wonder if we pass `orgName` through to the `vue add single-spa` command to be interpolated in that process instead (and leave the current `vue create` as-is).

**Comment by joeldenning** [comment]
> For 2, I wonder if we should pass orgName through to the vue add single-spa command to be interpolated in that process instead (and leave the current vue create as-is).

Interesting idea - that could maybe work for the set-public-path and package.json files. But it doesn't help with how Vue CLI will create nested directories when you provide a name with a slash in it. Ideally that would also be solved. And if we can avoid prompting the user for the org/project name multiple times, that would also be nice.

**Comment by filoxo** [comment]
Oh I wasn't meaning to include it in the `vue create` command. create-single-spa internally would end up doing the following:

- prompt for projectName
- prompt for orgName
- other prompts
- `vue create <projectName>`
- `vue add single-spa --org <orgName>`

so the generated directory doesn't contain the orgName (like other generated applications).

**Comment by joeldenning** [comment]
I see. Yeah that makes sense. For the last bullet point, I think that the org name would just be included in the package.json's `name` field, which is what vue-cli-plugin-single-spa currently uses when calling setPublicPath(). So If we can get the first four bullet points to work (without creating extra directories!), then I think the fifth is likely unnecessary.

**Comment by filoxo** [comment]
Oh even better!
