### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by KillBOSS-KillMe** [single-spa/create-single-spa#151]

**Comment by filoxo** [comment]
Hi @KillBOSS-KillMe. Are you asking for jQuery to be supported in create-single-spa? Unfortunately, jQuery usage has really declined over the last few years so we probably won't provide support for it in this utility. 

If you're asking how to work with single-spa and jQuery in applications, it is possible. Most applications can rely on globals as normal (as long as there is a single version), or you can modernize the approach and use [in-browser module approach](https://single-spa.js.org/docs/recommended-setup/#in-browser-versus-build-time-modules) (which is part of our recommended setup), or you might need [single-spa-leaked-globals](https://single-spa.js.org/docs/ecosystem-leaked-globals/) to help isolate multiple versions of global libraries. Hopefully this information can get you started!

**Comment by filoxo** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to respond or reopen if the question is not resolved fully.
