### ISSUE TITLE
Installing using preset - [Vue 3] babel, eslint - default install not working 

### ISSUE THREAD

**Issue by bernietai** [single-spa/create-single-spa#168]
The generated URL 

http://single-spa-playground.org/playground/instant-test?name=@[org-name]/single-spa-vue&url=%2F%2Flocalhost%3A8080%2Fjs%2Fapp.js&framework=vue

results in an error. See chrome javascript console

<img width="1038" alt="Screen Shot 2020-08-13 at 2 08 03 pm" src="https://user-images.githubusercontent.com/10083575/90093404-de10b780-dd6e-11ea-8056-bc7013556799.png">

Thanks for your help on this.

**Comment by filoxo** [comment]
I was able to reproduce this issue using these steps:

- `npx create-single-spa`
- ? Directory for new project .
- ? Select type to generate single-spa application / parcel
- ? Which framework do you want to use? vue
- ? Organization name (use lowercase and dashes) test
- ? Project name (use lowercase and dashes) project
- `cd project`
- `yarn serve`

Using npx above pulls down the latest version of create-single-spa, and my test used Vue CLI v4.5.3 which allows selecting "Default (Vue 3 Preview) ([Vue 3] babel, eslint)". There are quite a few breaking changes in Vue 3 which this plugin isn't updated to use yet.

- [removed config.productionTip](https://v3.vuejs.org/guide/migration/global-api.html#config-productiontip-removed). 
- [`createApp` replaces default export](https://v3.vuejs.org/guide/migration/global-api.html#a-new-global-api-createapp)

**Comment by filoxo** [comment]
single-spa-vue and vue-cli-plugin-single-spa (https://github.com/single-spa/single-spa-vue/pull/52 and https://github.com/single-spa/vue-cli-plugin-single-spa/pull/16 respectively) have both been updated with Vue 3 compatibility. I don't believe there's anything else to be done in create-single-spa to support Vue 3.
