### ISSUE TITLE
CLI gets terminated automatically after entering project name while create application in vue framework

### ISSUE THREAD

**Issue by abhi0990** [single-spa/create-single-spa#173]
I am trying to create a Single SPA application in vue by using create-single-spa cli. 
i am following below steps 

1.  npm install --global create-single-spa
2. create-single-spa
3.  ? Directory for new project -  vue-app-1
4. ? Select type to generate -  single-spa application / parcel
5. ? Which framework do you want to use? -  vue
6. ? Organization name (use lowercase and dashes) - vue-demo
7. ? Project name (use lowercase and dashes) -  vue-demo

After entering the project name the CLI gets terminated automatically. Its not proceeding further to create a new vue application. I tried the same for react and it worked fine. This problem i am facing with vue framework 

<img width="513" alt="Screen Shot 2020-09-08 at 1 44 15 PM" src="https://user-images.githubusercontent.com/33829784/92451768-cd6f2800-f1da-11ea-8941-b949d94debab.png">

**Comment by filoxo** [comment]
Can you provide the following: 
- version of nodejs
- version of npm
- version of vue-cli that you have globally installed

**Comment by abhi0990** [comment]
> Can you provide the following:
> 
> * version of nodejs
> * version of npm
> * version of vue-cli that you have globally installed

**Comment by abhi0990** [comment]
> Can you provide the following:
> 
> * version of nodejs
> * version of npm
> * version of vue-cli that you have globally installed

version of nodejs. - v10.16.3
version of npm - 6.12.0
version of vue-cli that you have globally installed - @vue/cli 4.5.3

**Comment by filoxo** [comment]
I think I was able to replicate the issue. It happens when a non-relative path is given as the `--dir` flag. A workaround would be to use a relative path like so `create-single-spa ./vue-app-1`. I'm still investigating why this is happening and will fix.

**Comment by filoxo** [comment]
I released this fix in [create-single-spa@1.12.5](https://github.com/single-spa/create-single-spa/releases/tag/v1.12.5).

**Comment by abhi0990** [comment]
> I released this fix in [create-single-spa@1.12.5](https://github.com/single-spa/create-single-spa/releases/tag/v1.12.5).

Thanks @filoxo for quick resolution
