### ISSUE TITLE
Cannot use numbers either in org or project name

### ISSUE THREAD

**Issue by painbfb** [single-spa/create-single-spa#177]
Hello,

I met an issue following a tutorial here: https://dev.to/thawkin3/developing-and-deploying-micro-frontends-with-single-spa-39ij

I think it's normal to use numbers in project name.

For example, org name like `back2warcraft`,  project name like `single-spa-demo-1` should be OK. 

I found probably it's becoz that cli `v1.12.3` made some breaking change? We cannot include numbers in project name any more.

See this line: https://github.com/single-spa/create-single-spa/blob/59d29ec41e2848a0e6c1b932bcc66504079c4127/packages/generator-single-spa/src/naming.js#L1

**Comment by filoxo** [comment]
I can agree with this. Perhaps we should use the same rules as required for [package.json name](https://docs.npmjs.com/files/package.json#name). Any concerns @joeldenning? 

Would you be willing to submit a PR @painbfb?

**Comment by joeldenning** [comment]
I agree that numbers should be allowed

**Comment by filoxo** [comment]
This functionality was released in [create-single-spa@1.13.0](https://github.com/single-spa/create-single-spa/releases/tag/v1.13.0).
