### ISSUE TITLE
Improve sourcemaps with devtoolModuleFilenameTemplate option

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#185]
See https://webpack.js.org/configuration/output/#outputdevtoolmodulefilenametemplate - this changes sourcemaps to be prefixed by the project name

**Comment by joeldenning** [comment]
Scratch that - adding https://webpack.js.org/configuration/output/#outputdevtoolnamespace would be better

**Comment by joeldenning** [comment]
https://github.com/single-spa/create-single-spa/blob/eb33916a34cbcbfe2d2029d8bcbd449d126b170c/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L30

**Comment by joeldenning** [comment]
@aurre is going to look into this

**Comment by aurre** [comment]
@joeldenning PR is up for this improvement.

**Comment by joeldenning** [comment]
Resolved in https://github.com/single-spa/create-single-spa/pull/212
