### ISSUE TITLE
Error when @angular/cli@8 is being used

### ISSUE THREAD

**Issue by filoxo** [single-spa/create-single-spa#186]
The issue was raised on Slack. See https://single-spa.slack.com/archives/C8R6U7MT7/p1601182403067100

When @angular/cli@8 is installed locally (and presumably versions below), create-single-spa errors with:

```sh
Unknown option: --package-manager
Unknown option: yarn.
```

<img width="1323" alt="Screenshot 2020-09-27 at 10 16 35 AM" src="https://user-images.githubusercontent.com/4202993/94449682-99e44580-0169-11eb-9270-c013d64843ed.png">

If you run `npx @angular/cli@8.3.29 new --help` you'll see that it doesn't have an option for `--package-manager` but the next version does (as verified by running `npx @angular/cli@9 new --help`).

**Comment by joeldenning** [comment]
Hmm should we disable the yarn question then if we detect angular < 9?

**Comment by filoxo** [comment]
Yea, that's likely the best solution.

**Comment by filoxo** [comment]
Actually, I'm more inclined to just remove the prompt for packageManager for Angular apps. I think it's more of a headache to deal with to parse the version of the angular/cli and conditionally do that logic. Any aversion to that? Only reason I can think of to keep it for is consistency with the other generators.

**Comment by joeldenning** [comment]
Will Angular prompt for package manager if we omit it? If so then that's completely fine with me.

**Comment by filoxo** [comment]
This change was published in [create-single-spa@1.14.1](https://github.com/single-spa/create-single-spa/releases/tag/v1.14.1).
