### ISSUE TITLE
Upgrade Webpack configs for Webpack 5

### ISSUE THREAD

**Issue by filoxo** [single-spa/create-single-spa#198]
[Webpack 5 has been released](https://webpack.js.org/blog/2020-10-10-webpack-5-release/). I'm opening this issue to 1) begin research into what changes are necessary in webpack-config-single-spa-* packages and if the plugins we use have also been updated, and 2) actually make the changes to be fully compatible with Webpack 5 to publish as a major version change. 

There are a few changes that seem relevant:

> You don’t need to use jsonpFunction anymore.  
>
> PublicPath will be determined automatically. I’m not sure if that means it will work with a systemjs setup or not though 

From: https://single-spa.slack.com/archives/C9JV40F7V/p1602394321086000

**Comment by adamlusted-swipejobs** [comment]
Webpack 5 is required for webpack module federation.

**Comment by joeldenning** [comment]
This is now released in 2.0

**Comment by filoxo** [comment]
Migration guide can be found in the discussion here: https://github.com/single-spa/create-single-spa/discussions/248
