### ISSUE TITLE
webpack config single-spa breaking existing code possibly due to the standalone plugin

### ISSUE THREAD

**Issue by tsukhu** [single-spa/create-single-spa#209]
The new changes seems to break the existing projects on upgrade to the new versions of the webpack plugin.

I upgraded my existing single spa app to use the latest versions of single-spa and see there is some issue due to the new `standalone plugin` even when I have not added it to my project

https://github.com/tsukhu/intermix-spa-portal/commit/b13f04069c32f240e49489caa0c3040a09dde782

When I do the build for the sub projects like yarn workspace dashboard build I see a new `index.html` file being added which was I believe specific for to the standalone plugin

![image](https://user-images.githubusercontent.com/846306/96837376-f5051180-1463-11eb-87c3-a3aa8db12c65.png)

Also now if you go to https://intermix-spa.netlify.app/ it works but the sub routes if directly accessed (not via the router link) they showing the standalone plugin html file

--- 
Do I need to do anything from my side if this is a breaking change ?

**Comment by joeldenning** [comment]
Hi @tsukhu - I did not consider the creation of an index.html file to be a breaking change, but see from your explanation how it could alter behavior. Perhaps one option could be to disable the HtmlWebpackPlugin and StandaloneSingleSpaPlugin if the [webpack mode](https://webpack.js.org/configuration/mode/#root) is production? Doing that would prevent the generation of the index.html file.

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/create-single-spa/releases/tag/v1.17.3
