### ISSUE TITLE
Unable to resolve bare specifier '@{company}/{package}'

### ISSUE THREAD

**Issue by Scott-Selke** [single-spa/create-single-spa#215]
Hello! I am having an issue with a simple program I have setup. I have a single-spa application setup and a root-config application ready to go. When I had the initial starter code running everything worked, but the second I added an internal package from my companies repo it broke the root-config bootstrapping and gave me this error: Unable to resolve bare specifier '@{company}/{package}'. Anything in particular I am doing wrong?

**Comment by filoxo** [comment]
single-spa-webpack-config uses a [regex to match all org packages](https://github.com/single-spa/create-single-spa/blob/master/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L90) and mark them as external. See also https://github.com/single-spa/create-single-spa/issues/109. This may be problematic if you have some packages you want to have in the import map and others locally installed. If you'd rather continue to use the org namespace as it's currently configured, then the package would need to be added to the import map and built using a compatible module format (UMD, AMD, or System).
Alternatively, this behavior can be toggled by passing in `orgPackagesAsExternal: false` ([documentation](https://single-spa.js.org/docs/create-single-spa/#usage)) to the webpack-config-single-spa your application's Webpack config depends on, and then manually defining the `externals` of your microfrontends' Webpack config. 

```js
const orgName = 'my-org'
const defaultConfig = singleSpaDefaults({
  orgName, // orgName defined above for reusability
  projectName: 'name-of-project',
  webpackConfigEnv,
  argv,     
  orgPackagesAsExternal: false, // Disables org scope in externals 
})
return webpackMerge.smart(defaultConfig, {
  externals: [ // Define individual packages that should be resolve in-browser (via SystemJS)
    `@${orgName}/app-1`,
    `@${orgName}/app-2`,
    `@${orgName}/app-3`,
      ...
  ] 
})
```

It'd be possible to take this a step further and publish a shared webpack-config package that your company uses that wraps single-spa-webpack-config and adds these externals. That would centralize that list to prevent repetition in every application's config.

**Comment by filoxo** [comment]
I believe the original question is answered so I'm going to close this issue, but feel free to ask additional questions.
