### ISSUE TITLE
support for custom templates

### ISSUE THREAD

**Issue by alfredosalzillo** [single-spa/create-single-spa#217]
There is support for **custom templates** like others create cli like [create-react-app](https://create-react-app.dev/docs/custom-templates/)?

**Comment by filoxo** [comment]
We don't support it directly in create-single-spa, but we use Yeoman which [enables Composability of generators](https://yeoman.io/authoring/composability.html). This way you can extend it to do what else you need it to. I'm not aware of anyone doing so yet but if there are changes to be made to create-single-spa to better support composability we'd be happy to review a PR.

**Comment by joeldenning** [comment]
Yeah you can create your own yeoman generator that extends the create-single-spa generators, but alters their behavior. When I authored this project, I chose Yeoman specifically to allow this.

**Comment by joeldenning** [comment]
Reopening this - it's something that I think a lot of organizations would like and benefit from. Several months ago I was hoping to create an example of this - perhaps I'll get to it at some point.
