### ISSUE TITLE
Vanilla app created with CLI fails "yarn build" with a @types/react conflict

### ISSUE THREAD

**Issue by lorenjerickson** [single-spa/create-single-spa#218]
I've run into a problem with conflicting @types declarations an a vanilla app created with the create-single-spa CLI.  There are two versions of @types/react referenced.  One at root of the package structure and one under @types/testing-library__react.  See an example error during the build below.

```
ERROR in /home/loren/dev/customer-portal/spa-deps-test/node_modules/@types/testing-library__react/node_modules/@types/react/index.d.ts
ERROR in /home/loren/dev/customer-portal/spa-deps-test/node_modules/@types/testing-library__react/node_modules/@types/react/index.d.ts(3166,13):
TS2717: Subsequent property declarations must have the same type.  Property 'textPath' must be of type 'SVGProps<SVGTextPathElement>', but here has type 'SVGProps<SVGTextPathElement>'.
```

Steps to reproduce:
1. `create-single-spa` 
2. follow the steps to create an app/parcel with typescript and yarn
3. run `yarn build` in the project directory
4. observe dozens of errors similar to the one above in the output

I've tried messing with the version of @types/react included at the root, but that ends up becoming a can of worms. Is there a way to work around this?  

Really like this tool btw, but this issue is blocking me from making any meaningful progress.

**Comment by PieterBoeren** [comment]
I also have similar issues (not the same error, but also related to the React typings) from time to time, I always solve it like this:

`npx yarn-deduplicate --packages @types/react yarn.lock`
`rm -Recurse -Force node_modules`
`yarn install`

**Comment by joeldenning** [comment]
I was able to reproduce the issue - it's related to using an old version of `@testing-library/react`.

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/create-single-spa/releases/tag/v1.17.6

**Comment by lorenjerickson** [comment]
Confirmed.  Thanks for the quick turn-around.
