### ISSUE TITLE
Implement generator for shared dependencies

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#23]

**Comment by filoxo** [comment]
Using the react-microfrontends org as an example, do the generated files look like the [shared-dependencies repo](https://github.com/react-microfrontends/shared-dependencies) or like the [styleguide repo](https://github.com/react-microfrontends/styleguide) instead?

**Comment by joeldenning** [comment]
shared-dependencies repo. The generator would simply create an `shared.importmap` file (`.importmap` file extension is what we should move towards).

The content of the import map should be something like this:

```json
{
  "imports": {
    "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@5.3.1/system/single-spa.min.js"
  }
}
```

**Comment by mellis481** [comment]
Looks like that CDN URL is no longer valid.  Is this the correct one? `https://cdn.jsdelivr.net/npm/single-spa@5.3.1/lib/umd/single-spa.min.js`

**Comment by filoxo** [comment]
The system build would be better with the recommended setup, but yea, it appears that one of the intermediary folders was missing from the URL.

https://cdn.jsdelivr.net/npm/single-spa@5.3.1/lib/system/single-spa.min.js

**Comment by joeldenning** [comment]
Good catch - updated my comment
