### ISSUE TITLE
Error: systemjs-webpack-interop: There is no such module '@example\root-config' in the SystemJS registry

### ISSUE THREAD

**Issue by luca-esse** [single-spa/create-single-spa#230]
**Installed version**
1.18.0
**OS**
Windows 10

**Describe the bug or question**
A brand new root-config created with create-single-spa throws a SystemJS error when loading the page.

**To Reproduce**
`$ npm install --global create-single-spa`
`$ create-single-spa`

Parameters used:
? Directory for new project .
? Select type to generate single-spa root config
? Which package manager do you want to use? npm
? Will this project use Typescript? Yes
? Would you like to use single-spa Layout Engine Yes
? Organization name (can use letters, numbers, dash or underscore) example

**Expected behavior**
The welcome page appears.

**Screenshots and/or console output**
`Uncaught (in promise) Error: systemjs-webpack-interop: There is no such module '@example\root-config' in the SystemJS registry. Did you misspell the name of your module?
    at setPublicPath (public-path.js:35)
    at Module.<anonymous> (resource-query-public-path.js:10)
    at Module../node_modules/systemjs-webpack-interop/resource-query-public-path.js?systemjsModuleName=@example\root-config&rootDirectoryLevel=1 (resource-query-public-path.js:10)
    at __webpack_require__ (bootstrap:19)
    at Object.1 (example-root-config.js:10018)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at Object.execute (bootstrap:83)
    at doExec (system.js:471)
    at postOrderExec (system.js:467)`

**Additional context**
When i replace "@example/root-config" with "@example\\\root-config" it works as expected (notice the slash).

Example:

This is the default and does not work:
`<script type="systemjs-importmap">
    {
      "imports": {
        "@single-spa/welcome": "https://unpkg.com/single-spa-welcome/dist/single-spa-welcome.js",
        "@example/root-config": "//localhost:9000/example-root-config.js"
      }
    }
  </script>`

`<script>
    System.import('@example/root-config');
</script>`

This works:
`<script type="systemjs-importmap">
    {
      "imports": {
        "@single-spa/welcome": "https://unpkg.com/single-spa-welcome/dist/single-spa-welcome.js",
        "@example\\root-config": "//localhost:9000/example-root-config.js"
      }
    }
  </script>`

`<script>
    System.import('@example\\root-config');
</script>`

**Comment by Abhishek-Kanitkar** [comment]
I am also facing the same issue @luca-esse. Did you find any solution to this ? :(

**Comment by luca-esse** [comment]
Hello, yes I’ve found the root cause of the problem. 
It seems that the latest version of SystemJS introduced a bug by using path.resolve on the module name, breaking the slashes on windows. I’m going to open a pull request asap

**Comment by luca-esse** [comment]
I've opened an issue on [systemjs-webpack-interop](https://github.com/joeldenning/systemjs-webpack-interop/issues/15)

**Comment by PieterBoeren** [comment]
For me, this only breaks when overriding apps (with the same error), probably because I use Linux for "production" and Windows for the overrides. But the result is the same: can't really develop at the moment without pushing and deploying the code to the "production" environment.

**Comment by joeldenning** [comment]
I just released https://github.com/joeldenning/systemjs-webpack-interop/releases/tag/v2.3.2 which has the fix. Let me know if you still run into issues after upgrading! webpack-config-single-spa should automatically install the latest version of systemjs-webpack-interop, due to semver ranges:

https://github.com/single-spa/create-single-spa/blob/147d2878d8ab50d442b617c702d7cce6e45ce481/packages/webpack-config-single-spa/package.json#L31

You can update your yarn.lock/package-lock.json to ensure that systemjs-webpack-interop@2.3.2 is used, or you can uninstall/reinstall webpack-config-single-spa which should ensure that the correct version is used.

**Comment by joeldenning** [comment]
My original fix didn't actually fix this. But https://github.com/joeldenning/systemjs-webpack-interop/releases/tag/v2.3.3 is confirmed to work in Windows.
