### ISSUE TITLE
Bug in build process of root config application 

### ISSUE THREAD

**Issue by chemaxa** [single-spa/create-single-spa#236]
**Describe the bug or question**
Hello. Thank you for your package. I tried to install and start the root config application and faced with bug in webpack build process.
Can you give me advice how to solve this issue.

**To Reproduce**
This is my demo github repository with issue 
https://github.com/chemaxa/single-spa-bug-report

I just create root config with command 

npx create-single-spa

and then run 

npm start

after that i got webpack errors in console

**Expected behavior**
No webpack errors.

**Screenshots and/or console output**
```

ERROR in multi ./D:/Repositories/VTB/smart-console/demo-console/node_modules/systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=@demo/root-config&rootDirectoryLevel=1 ./src/demo-root-config.ts
Module not found: Error: Can't resolve 'D:\Repositories\VTB\smart-console\demo-console/D:\Repositories\VTB\smart-console\demo-console\node_modules\systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=@demo/root-config&rootDirectoryLevel=1' in 'D:\Repositories\VTB\smart-console\demo-console'   
 @ multi ./D:/Repositories/VTB/smart-console/demo-console/node_modules/systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=@demo/root-config&rootDirectoryLevel=1 ./src/demo-root-config.ts main[0]

ERROR in multi (webpack)-dev-server/client?http://localhost:9000 ./D:/Repositories/VTB/smart-console/demo-console/node_modules/systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=@demo/root-config&rootDirectoryLevel=1 ./src/demo-root-config.ts
Module not found: Error: Can't resolve 'D:\Repositories\VTB\smart-console\demo-console/D:\Repositories\VTB\smart-console\demo-console\node_modules\systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=@demo/root-config&rootDirectoryLevel=1' in 'D:\Repositories\VTB\smart-console\demo-console'   
 @ multi (webpack)-dev-server/client?http://localhost:9000 ./D:/Repositories/VTB/smart-console/demo-console/node_modules/systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=@demo/root-config&rootDirectoryLevel=1 ./src/demo-root-config.ts main[1]
```
![2020-12-15_12-39-39](https://user-images.githubusercontent.com/9295022/102201275-ea508100-3ed6-11eb-97a6-bd159ad82995.png)
![2020-12-15_12-41-24](https://user-images.githubusercontent.com/9295022/102201281-eb81ae00-3ed6-11eb-8c08-3612072abfeb.png)

**Additional context**
Node 12.16.2
npm 6.14.4
Windows 10
Also i tried on Windows 7, node 12.8, npm 6.9 and got same bug.

**Comment by filoxo** [comment]
This isn't actually related to create-single-spa (at least not directly). The error originates from systemjs-webpack-interop, which has this same issue reported here: https://github.com/joeldenning/systemjs-webpack-interop/issues/17 closing in favor of that issue.

**Comment by joeldenning** [comment]
This is fixed in https://github.com/joeldenning/systemjs-webpack-interop/releases/tag/v2.3.3. To upgrade, you can modify your package-lock.json or yarn.lock, or you can uninstall and reinstall wepack-config-single-spa which should give you v2.3.3 of systemjs-webpack-interop.
