### ISSUE TITLE
TypeError: "Cannot read property readFile of undefined"

### ISSUE THREAD

**Issue by AnikaErceg** [single-spa/create-single-spa#24]
Steps taken:
Use command do create the spa
Choose create root config option
Select either Yarn or NPM.
Regardless of what is chosen, this error is thown
![image](https://user-images.githubusercontent.com/26693599/76191177-71095c80-61e7-11ea-8ca8-14473b238532.png)

Machine I am using has both yarn and npm installed.
If it makes any difference, I am using Linux Mint 18.3 Cinnamon.

**Comment by joeldenning** [comment]
create-single-spa requires nodejs@>=10, since it uses [fs.promises](https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_promises_api).

Please upgrade to at least node 10 and try again.
