### ISSUE TITLE
Use webpack prebuild rimraf instead of clean-webpack-plugin

### ISSUE THREAD

**Issue by MV10** [single-spa/create-single-spa#243]
As you know, the `clean-webpack-plugin` required by `webpack-config-single-spa` blindly deletes the output from any previous build.

This is a problem in our project because each app's webpack config overrides the per-app `dist` output directory to use a common build target. (This is basically a side-effect of our production CI/CD process which is limited to a simple zip/unzip operation after a Lerna-driven monorepo build.)

Since we like the other functionality of `webpack-config-single-spa` we have a fairly hacky call in each webpack config to remove this plugin from `defaultConfig.plugins`.

It occurs to me that it might be cleaner for `create-single-spa` to generate a webpack `prebuild` script using [rimraf](https://github.com/isaacs/rimraf), which would make it easy to opt-in or opt-out of this particular behavior. (Normally I'd offer to PR this, I try to contribute to OSS where I can, but I don't do any JS-based development at home, and unfortunately my work machine is heavily regulated and github access is blocked.)

**Comment by MV10** [comment]
All good points, thanks -- but shouldn't `filter` select everything _except_ the plugin to remove? (In case someone else lands on this issue...)

**Comment by joeldenning** [comment]
Good catch I've updated the code in my previous comment
