### ISSUE TITLE
Root config's import-map-overrides listed twice

### ISSUE THREAD

**Issue by MV10** [single-spa/create-single-spa#244]
Very  minor, but is this just an oversight that the `if (isLocal)` block of script tags and the `else` block are exactly the same? Since that's for development only, I've been pondering whether the `else` block should even be there...

https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/root-config/templates/src/index.ejs#L60

Does this also imply that the `systemjs` libs are only needed when `import-map-overrides` is in use? We're in banking and can't have internal apps pointing to public CDNs, so I've been revising our webpack config to copy things like react to a local `dist/lib` location for builds. I actually noticed this when I was deciding if I need to add those to the copy-local list.

**Comment by filoxo** [comment]
The script tags for import-map-overrides.js is the smae but the other two script tags load the non-minified version if `isLocal`, which is better for error messaging and debugging. So the first script could be moved out but I think was kept in there for consistency as well as in case someday import-map-overrides.js had an unminified version that was more helpful (as it is right now, there is only the one file). 

> Does this also imply that the systemjs libs are only needed when import-map-overrides is in use?

No, its the other way around. import-map-overrides depend on SystemJS, but that script itself is a custom element so the actual overrides logic doesn't get executed until the CE is instantiated (here https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/root-config/templates/src/index.ejs#L75). In other words, the order of it in relation to the SystemJS script tags doesn't really matter (I believe, I could still be wrong but that's my current understanding).

**Comment by MV10** [comment]
Oops, overlooked the "min"! Thanks for the clarifications.

**Comment by joeldenning** [comment]
> In other words, the order of it in relation to the SystemJS script tags doesn't really matter (I believe, I could still be wrong but that's my current understanding).

Yes, this is correct. The `<import-map-overrides-full>` web component can be anywhere in the DOM
