### ISSUE TITLE
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "import-map-overrides-full" has already been used with this registry

### ISSUE THREAD

**Issue by hackftz** [single-spa/create-single-spa#254]
hello, I upgrade create-single-spa to v2.0.2, then I got the dom exception like this:

![image](https://user-images.githubusercontent.com/33424860/105132138-57ce7d80-5b25-11eb-9279-c86fba8e6fbf.png)

my operation:
1. run npm run start in shell
2. visit localhost:9000

repo: https://github.com/hackftz/funs-single-spa-config

I didn't moditfy any code or file, so what can I do to fix it, thks!

**Comment by PieterBoeren** [comment]
Not sure if it helps, but your code seems to import "import-map-overrides.js" twice, both on line 72 and 77 (index.ejs). Could you remove the one on line 77 and try again?

**Comment by hackftz** [comment]
it helpful, thks!

**Comment by joeldenning** [comment]
It is expected and normal for there to be two import-map-overrides in the index.ejs. They are in an if-else for based on the `isLocal` flag.

The root cause of this problem was #250, which was solved in #251. To fix your existing project, make the same change as what you see in #251 to your root config's webpack.config.js. Once you do that, it will work.

**Comment by PieterBoeren** [comment]
@joeldenning , why are there two different versions then? I've created a new rootconfig (with layout engine enabled) with 2.0.2 and it looks like this:

```<script src="https://cdn.jsdelivr.net/npm/import-map-overrides@2.2.0/dist/import-map-overrides.js"></script>
  <% if (isLocal) { %>
  <script src="https://cdn.jsdelivr.net/npm/systemjs@6.8.2/dist/system.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/systemjs@6.8.2/dist/extras/amd.js"></script>
  <% } else { %>
  <script src="https://cdn.jsdelivr.net/npm/import-map-overrides@1.16.0/dist/import-map-overrides.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/systemjs@6.8.2/dist/system.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/systemjs@6.8.2/dist/extras/amd.min.js"></script>
  <% } %>```

I see version 2.2.0 and 1.16.0 and why is the first one not in the "isLocal" branch? And shouldn't the last one be minified?

**Comment by joeldenning** [comment]
The version mismatch is just an oversight / bug that happened when we upgraded the dependencies. It should be fixed. However, the version mismatch doesn't cause the bug described in the original post. Feel free to submit a pull request to fix the version issue

**Comment by PieterBoeren** [comment]
I'm will submit a PR to fix this, but I also see differences between the two index.ejs files (https://github.com/single-spa/create-single-spa/blob/main/packages/generator-single-spa/src/root-config/templates/src/index.ejs and the one in the layout folder). Also related to the issue mentioned above, which is the correct one?

**Comment by joeldenning** [comment]
Both index.ejs files should use the latest version of import map overrides, systemjs, and single-spa. One is for projects that use single-spa-layout, and the other is for projects that don't.

**Comment by PieterBoeren** [comment]
I get that, but is there is reason the the "layout" one has two script tags for the "import-map-overrides.js" file and the other not?

**Comment by joeldenning** [comment]
Ah I see now what you've been saying. I misread the code earlier and what I said was wrong. I thought that import-map-overrides was in both the if and the else, but see now that it's only in the else.

So what you've been saying all along is right - we should remove the script tag for import map overrides from the else branch. Thanks for walking me through this - am happy to review a PR for it.

**Comment by PieterBoeren** [comment]
Created https://github.com/single-spa/create-single-spa/pull/255

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/create-single-spa/releases/tag/v2.0.3
