### ISSUE TITLE
Error during first start of root-config 

### ISSUE THREAD

**Issue by sfrinx** [single-spa/create-single-spa#261]
I try the quick start guide and after install I receive this error and the root config not start.

ERROR in   Error: The loader "./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs" didn't return html.
  
  - index.js:336 HtmlWebpackPlugin.evaluateCompilationResult
    [fake-root]/[html-webpack-plugin]/index.js:336:24
  
  - index.js:243 Promise.resolve.then
    [fake-root]/[html-webpack-plugin]/index.js:243:22
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7

**Comment by joeldenning** [comment]
Hi @sfrinx, I was able to reproduce the problem. It seems related to a new version of webpack not supporting old versions of html-webpack-plugin. The good news is that we don't need to use an old version of html-webpack-plugin - we were only doing so accidentally. I'll put together a fix.

**Comment by joeldenning** [comment]
I believe this was caused by webpack@5.22.0, which was released 9 hours ago. See https://github.com/webpack/webpack/releases/tag/v5.22.0.

I have fixed it in #262

**Comment by ptallett** [comment]
How do I pick up this fix?

**Comment by joeldenning** [comment]
This is released in https://github.com/single-spa/create-single-spa/releases/tag/v2.1.1.

For existing projects, you can uninstall `html-webpack-plugin` to get the fix:

```sh
npm uninstall html-webpack-plugin

yarn remove html-webpack-plugin
```
