### ISSUE TITLE
React-based utility modules

### ISSUE THREAD

**Issue by MV10** [single-spa/create-single-spa#264]
Perhaps `create-single-spa` should ask if a new utility module needs framework support (in our case React) so that the webpack config will be generated with the correct package dependency.

We had some React components that were being re-used heavily, so we decided to put them into a utility module and pre-load it from the root-config. I ran `create-single-spa` and got everything set up, moved the components over and exported them, and to my dismay React started crashing with the misleading [Invalid Hook Call](https://reactjs.org/warnings/invalid-hook-call-warning.html) error. That led to [this](https://github.com/facebook/react/issues/13991) enormous, years-long thread-of-misery, and all I could tell for sure is that multiple _copies_ of React were being loaded (complicated by the fact that most people seem to be fighting multiple _versions_ of React, which isn't possible in our hoisted monorepo).

Anyway, as I'm sure you've guessed, the problem is that the utility's webpack config was generated by `webpack-config-single-spa`, and the fix was to instead require `webpack-config-single-spa-react` which declares React as a webpack external.

Considering (a) the error message from React is terrible and misleading (it has nothing to do with hooks...), (b) troubleshooting the problem is difficult at best, and (c) I only recognized the solution (after several hours) because I'd previously dug into the single-spa config packages -- this seems like something people could lose a lot of time chasing, which might be easily avoided with a simple change to the script.

**Comment by joeldenning** [comment]
I'm open to this. Supporting vue / angular utility modules would be a bit trickier since it's not just changing up the package.json dependencies and then using `webpack-config-single-spa-react` instead of `webpack-config-single-spa`. But we could start with just support for react and then add support for the others later. Maybe a yeoman prompt that asks "Framework for utility module" with current options being "React" and "No Framework"

**Comment by MV10** [comment]
Normally I would offer to help, but I'm not set up for npm or JS-anything at home, and the office machines where I do use this are firewalled to death (read-only access to GitHub, can't even create a login). Besides I'm such a n00b to the JS world you probably don't want me in your code anyway 😁

**Comment by joeldenning** [comment]
Ok in that case we'll just keep it open until maybe myself, Carlos, or someone else gets to it.

**Comment by huntz20** [comment]
i got same issue after while checking working configuration and finnaly add this line on your webpack.config.js

```
{
...
 externals: ["react", "react-dom"],
 
 }
```

**Comment by Vahn84** [comment]
God...you really don't know how much i love you right now. Got stuck into this for the last 9/10 hours. I understood what was the problem, but setting react and react-dom as externals didn't do the trick. Switching from webpack-config-single-spa to webpack-config-single-spa-react just solved the problem

Don't know why...i didn't event think about it

Thanks mate

**Comment by joeldenning** [comment]
Had some time today so I implemented this in #317

**Comment by joeldenning** [comment]
This is released in [create-single-spa@4.0.0](https://github.com/single-spa/create-single-spa/blob/main/packages/create-single-spa/CHANGELOG.md#400). The generated react utility modules create an unused root.component.tsx which might be something we could improve in the future, but overall the feature is working.

**Comment by GorkemSahin** [comment]
> I understood what was the problem, but setting react and react-dom as externals didn't do the trick. Switching from webpack-config-single-spa to webpack-config-single-spa-react just solved the problem
> 
> Don't know why...i didn't event think about it


I would really love to understand why it did not work. Just spent an entire day trying to figure this out.

**Comment by MilanKovacic** [comment]
Can you please specify exactly what you were trying to do?
webpack-config-single-spa-react is just a thin layer over webpack-config-single-spa: https://github.com/single-spa/create-single-spa/blob/main/packages/webpack-config-single-spa-react/lib/webpack-config-single-spa-react.js
