### ISSUE TITLE
Is it possible to remove "Your MicroFrontend is not here" message in production?

### ISSUE THREAD

**Issue by jrtitus** [single-spa/create-single-spa#265]
**Describe the bug or question**
How can I remove this content from rendering in a **production** environment if someone tries to navigate to an application root? 

My root-config is running on port 8080 from `dist`. The screenshot below shows what happens if I navigate to port 8081 (application running from its own `dist`).

I'm sorry if this information exists in the documentation and I missed it. 😅

**Screenshots and/or console output**
![image](https://user-images.githubusercontent.com/1756049/109815688-ebec3400-7bfd-11eb-9895-563c7f064a27.png)

**Comment by filoxo** [comment]
Our config is setup only include/build that when in development mode. See:

https://github.com/single-spa/create-single-spa/blob/0861b9056c20b70fc7d8128d6b08daa377ec1b95/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L99-L107

Your screenshot is also showing that you're serving locally and also not in development mode. If you also want to remove it from your development workflow you can do so by providing `disableHtmlGeneration: false` to our Webpack config options (https://single-spa.js.org/docs/create-single-spa/#usage).

**Comment by joeldenning** [comment]
Another option is to set `disabled: true` on the standalone plugin itself? Both `disableHtmlGeneration` and `disabled` would work

https://github.com/single-spa/standalone-single-spa-webpack-plugin#usage

**Comment by jrtitus** [comment]
Hi @filoxo. Thank you for taking the time to respond. I am serving from within a container running on my PC. 

I use `npm run build` (`vue-cli-service build`) and then copy the contents of `dist` to the container. That _should_ be running a production build. (Just to make sure, I set `configureWebpack.mode` equal to `'production'` in my `vue.config.js` file, and see the same result)

In my root-config `webpack.config.js` file I have `disableHtmlGeneration: true`. I do not wish to remove this generated content from the development workflow - only when serving an application in a production environment.

Is there something I am misunderstanding?

**Comment by jrtitus** [comment]
Hi @joeldenning. Thank you for responding. The page that appears says that the standalone plugin is already disabled:

> The @myorg/org-nav microfrontend is running in "integrated" mode, since standalone-single-spa-webpack-plugin is disabled. This means that it does not work as a standalone application without changing configuration.

This is what I want; I just do not want the page with the instructions to appear in production if someone navigates to the address hosting the app.

**Comment by filoxo** [comment]
Ah, I see. I assumed you were using our shared Webpack configs but Vue does not. In the Vue-cli plugin, we're relying on `process.env.STANDALONE_SINGLE_SPA`. 

https://github.com/single-spa/vue-cli-plugin-single-spa/blob/e3746601a76346f6b12bc8b3e756b93ae656ae88/index.js#L44

So it should just be setting that to anything that doesn't equal `"true"` on your .env file or unsetting it. Its been a minute since I've contributed to the vue plugin so I'm just catching up 😅

**Comment by joeldenning** [comment]
Oops you're right, `disable: true` doesn't do what you want - it shows the disabled screen.

For vue apps, you can just remove the plugin in your vue.config.js:

```js
// vue.config.js
module.exports = {
  chainWebpack(config) {
    config.plugins.delete('StandaloneSingleSpaPlugin')
  }
}
```

**Comment by jrtitus** [comment]
Thank you, @joeldenning. This is what I'm using now and it looks like it works, showing a blank page instead of the helper text:
```js
module.exports = {
  chainWebpack(config) {
    if (process.env.NODE_ENV === 'production') {
      config.plugins.delete('StandaloneSingleSpaPlugin')
    }
  },
}
```
Just FYI - it does throw an error in the console when doing this, but that might be necessary?
![image](https://user-images.githubusercontent.com/1756049/109851904-354e7a80-7c22-11eb-8e1e-538aa487b159.png)

**Comment by joeldenning** [comment]
>  it does throw an error in the console when doing this, but that might be necessary?

This is because html-webpack-plugin doesn't properly load microfrontends without the standalone plugin. If you'd like to disable generation of the html file entirely, you can delete html-webpack-plugin from your vue-config, too.
