### ISSUE TITLE
Loading images in a React Component

### ISSUE THREAD

**Issue by luca-sacco** [single-spa/create-single-spa#272]
Hi everyone!
I've created a React micro-front-end via the create-single-spa CLI. Everything worked great until I needed to import an image into a component. It seems that the plugin for uploading files is missing in the standard configuration of Webpack.

This is my **webpack.config.js**:
```
const path = require('path');

const { merge } = require('webpack-merge');
const singleSpaDefaults = require('webpack-config-single-spa-react-ts');

module.exports = (webpackConfigEnv, argv) => {
  const defaultConfig = singleSpaDefaults({
    orgName: 'main',
    projectName: 'single-spa',
    webpackConfigEnv: { webpackConfigEnv, standalone: true },
    argv,
  });

  return merge(defaultConfig, {
    output: {
      ...defaultConfig.output,
      filename: 'main.js',
      path: path.resolve(__dirname, 'dist', 'adsp-header'),
    },
  });
};
 
```

Could you help me understand how to add the functionality to import images into components? And then to be able to do this in the component: 

`import logo from '../../assets/logo.png';`

Thanks!

"single-spa-react": "^4.0.0",

**Comment by PieterBoeren** [comment]
Please note that the file-loader is considered deprecated in webpack 5, alternative is in the link above.

**Comment by PieterBoeren** [comment]
I can create a PR to add this (after Easter), but I'm unsure where to put the Typescript types for the images. Can you point out the best location for those @joeldenning?

**Comment by joeldenning** [comment]
Here's the file to add the typescript types to: https://github.com/single-spa/create-single-spa/blob/main/packages/generator-single-spa/src/common-templates/typescript/declarations.d.ts

**Comment by PieterBoeren** [comment]
Are the instructions for creating PR's still correct? In the contributing file it states to run "pnpmx changeset", but that command can't be found and the only thing I can find about "pnpmx" is some kind of vague terminal package. Running "pnpm changeset" gives me an error, but "yarn changeset" is working. So now I'm confused :)

**Comment by joeldenning** [comment]
It is `pnpx`, not `pnpmx`

**Comment by joeldenning** [comment]
I've created https://github.com/single-spa/create-single-spa/pull/275 to fix the typo in the contributing documentation

**Comment by PieterBoeren** [comment]
Thanks for the clarification :) Created #276 to add support for loading images.

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/create-single-spa/releases/tag/v2.3.0
