### ISSUE TITLE
Project startup instructions when using pnpm are incorrect

### ISSUE THREAD

**Issue by PieterBoeren** [single-spa/create-single-spa#278]
When creating a new single-spa application with npmn (I used Typescript, but that shouldn't matter) the instructions to start the project are not working. It states "Run 'pnpm start --port 8500'", but this gives an error: 

```"Unknown option: 'port'".```

I guess it is not passing the option to the start script, I worked around it by adding the port directly inside the start script ("start": "webpack serve --port 8500").

**Comment by joeldenning** [comment]
You can run `pnpm start -- --port 8500` to get it to work. I'll put together a pull request fixing the console output

**Comment by PieterBoeren** [comment]
I did close it myself, but this is still broken:

 ERROR   ERROR  Unknown option: 'port'
Did you mean 'sort'? Use "--config.unknown=value" to force an unknown option.

**Comment by joeldenning** [comment]
I tried it just now and it worked for me. Here's my output:

```sh
~/c/css-test (main|…) $ pnpm start -- --port 8500

> @org/project@ start /Users/joeldenning/code/css-test
> webpack serve "--port" "8500"

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8500/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.253:8500/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8500/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/joeldenning/code/css-test/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
asset org-project.js 389 KiB [emitted] (name: main) 1 related asset
asset index.html 3.05 KiB [emitted]
runtime modules 25.7 KiB 13 modules
modules by path ./node_modules/.pnpm/ 317 KiB
  modules by path ./node_modules/.pnpm/webpack-dev-server@4.0.0-beta.3_webpack-cli@4.7.0+webpack@5.36.2/node_modules/webpack-dev-server/client/ 157 KiB 13 modules
  modules by path ./node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.7.0/node_modules/webpack/hot/*.js 4.3 KiB 4 modules
  modules by path ./node_modules/.pnpm/html-entities@2.3.2/node_modules/html-entities/lib/*.js 81.3 KiB 4 modules
  modules by path ./node_modules/.pnpm/systemjs-webpack-interop@2.3.6_webpack@5.36.2/node_modules/systemjs-webpack-interop/ 3.4 KiB 3 modules
  modules by path ./node_modules/.pnpm/querystring@0.2.0/node_modules/querystring/*.js 4.51 KiB 3 modules
  modules by path ./node_modules/.pnpm/single-spa-react@4.1.1_react@17.0.2/node_modules/single-spa-react/lib/esm/*.js 10.2 KiB 2 modules
  modules by path ./node_modules/.pnpm/url@0.11.0/node_modules/url/*.js 23.1 KiB 2 modules
  3 modules
modules by path ./src/*.js 782 bytes
  ./src/org-project.js 534 bytes [built] [code generated]
  ./src/root.component.js 248 bytes [built] [code generated]
external "react" 42 bytes [built] [code generated]
external "react-dom" 42 bytes [built] [code generated]
webpack 5.36.2 compiled successfully in 1381 ms
```

Could you share your pnpm version, and a github repository that demonstrates it not working?

**Comment by PieterBoeren** [comment]
Sorry for the delay, but I just create a new application with version 2.2.3 of create-single-spa (TypeScript, React) and once I get this:

```
Project setup complete!
Steps to test your React single-spa application:
1. Run 'pnpm start -- --port 8500'
2. Go to http://single-spa-playground.org/playground/instant-test?name=@test/pnpminstructions&url=8500 to see it working!
D:\Dev\Temp\SingleSpa> cd .\pnpminstructions\
D:\Dev\Temp\SingleSpa\pnpminstructions> pnpm start -- --port 8500
 ERROR   ERROR  Unknown option: 'port'
Did you mean 'sort'? Use "--config.unknown=value" to force an unknown option.
For help, run: pnpm help run
```

pnpm version 6.3.0, running on Windows 10

**Comment by PieterBoeren** [comment]
A, I found the issue: https://github.com/pnpm/pnpm/issues/2134, it's a PowerShell "feature". This does work (notice the extra quotes):

```pnpm start "--" --port 8500```

Maybe the message you get after creating a project can be extended with something like "or 'pnpm start "--" --port 8500' when using PowerShell"?

**Comment by joeldenning** [comment]
> Maybe the message you get after creating a project can be extended with something like "or 'pnpm start "--" --port 8500' when using PowerShell"?

Sure - would you like to submit the pull request? Here's the file to modify:

https://github.com/single-spa/create-single-spa/blob/70226ef075afa35c2cbe3e07071b3859796075ac/packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js#L174

https://github.com/single-spa/create-single-spa/blob/70226ef075afa35c2cbe3e07071b3859796075ac/packages/generator-single-spa/src/react/generator-single-spa-react.js#L210

**Comment by PieterBoeren** [comment]
Sure, I'll try to find some time for this somewhere this week.
