### ISSUE TITLE
husky hooks don't work at first

### ISSUE THREAD

**Issue by TheMcMurder** [single-spa/create-single-spa#28]
Because the project isn't initialized as a git repo the husky hooks don't seem to work until you run
`git init`
`npm install husky --dev` or `yarn add husky --dev`

I think the best way to fix this is to run `git init` before installing dependencies

**Comment by joeldenning** [comment]
`git init` is a no-op when you're already in a git repository, right?

**Comment by TheMcMurder** [comment]
Yes

**Comment by joeldenning** [comment]
Resolved in #31
