### ISSUE TITLE
Output declarations by default on utility modules

### ISSUE THREAD

**Issue by vongohren** [single-spa/create-single-spa#289]
On utility module making, there should be templated so that the declarations are created by default.
Right now there is no documentation or simple way to get declartions. One have to set it up self.
This issue was raised: https://github.com/single-spa/single-spa.js.org/issues/361#issuecomment-827027568

And it was agreed that declarations should be on by default for utility modules.

Right now I dont have time to add it, as Im raising forward to get our rebuild up and running and ready for release. If I find the time I will come back and fix it.

But the issue is here for a tracker.

**Comment by joeldenning** [comment]
I may be able to get to this in the next couple weeks. If anyone else would like to contribute a PR for it, that would be welcome, too.

**Comment by gwinnem** [comment]
Hi Joel, any progress with this yet ?

**Comment by joeldenning** [comment]
No

**Comment by joeldenning** [comment]
I had some time today so I implemented this in #316

**Comment by joeldenning** [comment]
This is released in [ts-config-single-spa@3.0.0](https://github.com/single-spa/create-single-spa/blob/main/packages/ts-config-single-spa/CHANGELOG.md#300)

Projects generated with the latest version of create-single-spa will automatically generate types. The link above has documentation for migrating existing projects.
