### ISSUE TITLE
ESLint couldn't find the config "important-stuff" to extend from.

### ISSUE THREAD

**Issue by KayhanB** [single-spa/create-single-spa#295]
Hello

when i run "npm run lint" in react project which is created by create-single-spa cli i'm  getting this error => "ESLint couldn't find the config "important-stuff" to extend from."

- - - - - -
Project created as javascript project. eslint working with .ts create-single-spa template  but not working with js template

**Comment by joeldenning** [comment]
I'm unable to reproduce this - seems like you figured it out though since it's now closed.

**Comment by lukasrybacki** [comment]
Hej @KayhanB facing the same issue here. How did you solve this?
