### ISSUE TITLE
Failure in creating a new angular application

### ISSUE THREAD

**Issue by navrudh** [single-spa/create-single-spa#296]
**Describe the bug or question**
Creating a new project with the angular framework is broken

**To Reproduce**
npx create-single-spa --framework angular

**Expected behavior**
Should create an angular starter application

**Screenshots and/or console output**
Does not create a starter application, fails with the following message
```
Cannot open assembly 'new': No such file or directory.
```
![Issue Screenshot](https://user-images.githubusercontent.com/6846916/119970596-39373200-bfb0-11eb-9e1d-3c51b5aedd26.png)

**Additional context**
OS: PopOS 20.10
node version: v14.17.0

**Comment by joeldenning** [comment]
I was unable to reproduce this problem - do you have angular cli installed globally? If so, which version? If not, can you tell which version of Angular is being used via the terminal output? Angular 12 isn't fully supported yet - see https://github.com/single-spa/single-spa-angular/pull/362

**Comment by navrudh** [comment]
There is no global angular-cli installed on my machine.

I can confirm that I still get this issue.

**Comment by navrudh** [comment]
I tried from inside a docker container and it works. So something in the npm tooling must have broken on my setup. So closing this issue.
