### ISSUE TITLE
Error in unmount after create parcel

### ISSUE THREAD

**Issue by tacnoman** [single-spa/create-single-spa#304]
Hello everyone

I'm just following the `npx create-single-spa` to build my parcel component using react and js
I runned `yarn start --port 8500` and tried to open the url generated to test: `http://single-spa-playground.org/playground/instant-test?name=@company/react-single&url=8500`

The browser returned these two errors:
![Captura de Tela 2021-07-01 às 18 33 58](https://user-images.githubusercontent.com/5348316/124192065-13171d00-da9b-11eb-9bad-bdd9f0e4ffb8.png)

```
single-spa minified message #37: See https://single-spa.js.org/error/?code=37&arg=application&arg=@company/react-single&arg={} Module {Symbol(Symbol.toStringTag): "Module"}
```

```
Uncaught Error: application '@company/react-single' died in status LOADING_SOURCE_CODE: undefined
    at l (app-errors.js:87)
    at a (app-errors.js:6)
    at load.js:113
```

The url generated in error show me that the problem is the method unmount, but this method exists and was generated by `create-single-spa`:

```js
import React from "react";
import ReactDOM from "react-dom";
import singleSpaReact from "single-spa-react";
import App from "./App";

const lifecycles = singleSpaReact({
  React,
  ReactDOM,
  rootComponent: App,
});

export const { bootstrap, mount, unmount } = lifecycles;
```

I searched about this error and some people said that probably is a webpack error. My version of webpack:

```json
  //. package.json
    "webpack": "^5.40.0",
    "webpack-cli": "^4.7.2",
    "webpack-config-single-spa-react": "^2.2.2",
    "webpack-dev-server": "^4.0.0-beta.0",
    "webpack-merge": "^5.8.0"
  },
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "single-spa-react": "^4.2.0"
  }
}
```

Someone can help me to build my parcel?

Thanks for this

**Comment by jiteshkrishnan** [comment]
Faced a similar issue. I guess this was due to a patch release made 4 days back by the webpack team -webpack@5.41.1.  Again 2 days back a new minor release was made - webpack@5.42.0. Upgrading to this latest version worked for me

**Comment by tacnoman** [comment]
Worked for me @jiteshkrishnan :)

Thanks for this
