### ISSUE TITLE
webpack-config-single-spa-react doesn't support .jsx files

### ISSUE THREAD

**Issue by Tiberriver256** [single-spa/create-single-spa#305]
The entry is hardcoded to the .js file extension here:

https://github.com/single-spa/create-single-spa/blob/72f26a8327e8a2ee2de5c6855f93991d5cdef8f4/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L40

Suggestion would be to change that line to the following and let Webpack figure out the appropriate file extension:

```js
src/${opts.orgName}-${opts.projectName}
```

Based on the value of entry, webpack seems to search for a matching file in the following order:
[filename]
[filename].mjs
[filename].js
[filename].jsx
[filename].wasm
[filename].json

**Comment by joeldenning** [comment]
Agreed - i'll put together a fix.

**Comment by joeldenning** [comment]
Released in webpack-config-single-spa@3.1.0. See https://github.com/single-spa/create-single-spa/blob/main/packages/webpack-config-single-spa/CHANGELOG.md#310
