### ISSUE TITLE
About the path normal jump but the page did not update the problem

### ISSUE THREAD

**Issue by xianglihui** [single-spa/create-single-spa#311]
Hello, please ask a question about 'single SPA'. When my 'NAV' project jumps to the page (click the browser to return), the page URL changes, but the page does not change. Can you help me to answer this question? Or branch, thank you
https://github.com/xianglihui/single-spa-vue3.0-nav
![111](https://user-images.githubusercontent.com/84391514/126321537-29ba5878-c86f-4913-b856-a44ae8c4fe6b.png)
![222](https://user-images.githubusercontent.com/84391514/126321551-1f9cc7d2-1002-468e-a43e-de9586f7c005.png)
![333](https://user-images.githubusercontent.com/84391514/126321560-8a9d7ac4-e5fc-4484-bf8a-60c7ddf4f863.png)

**Comment by joeldenning** [comment]
I cloned the repository and see the problem, but do not have time to fully diagnose the issue right now. I will do so in the next week or so.

I've created https://github.com/xianglihui/single-spa-vue3.0-nav/pull/1 which fixes some issues in running the project, and provides instructions for doing so.

**Comment by joeldenning** [comment]
I've confirmed it's a bug in vue-router. I created https://github.com/xianglihui/single-spa-vue3.0-nav/pull/2 as a workaround for the bug, but will also create a bug in the vue-router Github to track this.

**Comment by xianglihui** [comment]
I think refreshing any page will trigger "router. BeforeEach" twice. It can also be said that the problem of refreshing two routes has something to do with "popstate". Perhaps the solution is to manually unload the components every time you jump to the page. Finally, we look forward to a more perfect solution.thank you very much

**Comment by xianglihui** [comment]
So my last question (refresh the page and update the route twice) was also caused by 'popstate'?
https://github.com/single-spa/create-single-spa/issues/307

**Comment by xianglihui** [comment]
Maybe I didn't describe it clearly. Please take a look at the GIF diagram. Is this a 'router' listening once in the forward direction and once in the reverse direction?
https://github.com/xianglihui/single-spa-vue3.0-Authority
![router1](https://user-images.githubusercontent.com/84391514/126854989-7169c69b-5b0d-4778-b367-8bdb2eeb0c7c.gif)

**Comment by joeldenning** [comment]
> So my last question (refresh the page and update the route twice) was also caused by 'popstate'?

I do not see a page reload when I transition from `/authority/role` to `/authority/permission`

> Is this a 'router' listening once in the forward direction and once in the reverse direction?

No. Route listeners listen to both forward and backward events.

**Comment by joeldenning** [comment]
I made a related fix at https://github.com/single-spa/single-spa-vue/issues/85.

See https://github.com/single-spa/single-spa-vue/issues/85#issuecomment-896372817 for instructions to try this out - you need to use vue-cli-plugin-single-spa@3
