### ISSUE TITLE
Building a TypeScript application fails due to new declarations output

### ISSUE THREAD

**Issue by PieterBoeren** [single-spa/create-single-spa#318]
1. Create a new application with TypeScript (with pnpm and React in my case)
2. Execute a build

Resulting in this error:
[build:types] tsconfig.json(5,5): error TS5069: Option 'declarationDir' cannot be specified without specifying option 'declaration' or option 'composite'.

**Comment by rams23** [comment]
The problem seems to be related to the ts-config-single-spa version, it should be updated to 3.0.0

**Comment by joeldenning** [comment]
Thanks for the bug report and the suggested fix. This was fixed in #320 and released in create-single-spa@4.0.1

**Comment by joeldenning** [comment]
Projects generated by create-single-spa@4.0.0 need to upgrade to ts-config-single-spa@3. Those with 4.0.1 will automatically have ts-config-single-spa@3
