### ISSUE TITLE
start with a gitignore

### ISSUE THREAD

**Issue by TheMcMurder** [single-spa/create-single-spa#32]
I think we should initialize the created repos with a gitignore file. 

Perhaps something simple like this:

```
# logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
# dependencies
node_modules

# OS stuff
.DS_Store
```

**Comment by joeldenning** [comment]
Github's default gitignore for NodeJS projects might be suitable. Here's an example: https://github.com/joeldenning/import-map-overrides/blob/master/.gitignore
