### ISSUE TITLE
Bug: nullish coalescing operator (??)

### ISSUE THREAD

**Issue by luzuoquan** [single-spa/create-single-spa#332]
As <code>generator-single-spa</code> has a nested dependency <code>inquirer</code> use the nullish coalescing operator(??), so it don't support node 12. throw a error below:

![image](https://user-images.githubusercontent.com/5476455/133438062-56b82f9b-e6c1-400d-ae7e-0c2f4ee6f010.png)

same as [bug](https://github.com/SBoudrias/Inquirer.js/issues/1046)

**Comment by joeldenning** [comment]
Thanks for pointing this out, I think the best solution would be to increase our minimum required nodejs version to node 14. Node 12 still has LTS support into 2022 but I don't think it's worth it or possible for us to have to downgrade inquirer trying to find a version that works with node 12.

Here's the place where we do the version check:

https://github.com/single-spa/create-single-spa/blob/42f8b6167f7afe64a9dc28fbfe96282cbfde16ea/packages/create-single-spa/bin/create-single-spa.js#L12-L13

**Comment by filoxo** [comment]
See also https://github.com/SBoudrias/Inquirer.js/issues/1046#issuecomment-919741423. This might be fixed before we have to do anything for it, as it was not an intended breaking change and (will most likely) be fixed as a patch version.

**Comment by joeldenning** [comment]
Ah good find, looks like maybe they'll revert it in which case we just would need to wait for the fix.
