### ISSUE TITLE
Adding support to scss and css module support with single spa react app boilerplate

### ISSUE THREAD

**Issue by cah-nagaraj-vemula** [single-spa/create-single-spa#337]
I was exploring a single spa for my project. I was using create-single-spa CLI for creating apps. To isolate the CSS in we tried using CSS modules. 
but we were not able to load CSS modules like we do with the create-react-app boilerplate
we were getting following error even after adding `css-loader`, `style-loader` and `scss-loader`

`WEBPACK_IMPORTED_MODULE_0__.default is undefined`

Shipping CSS module support with react app/parcel template would be really helpful to the developers(who is not expert in web pack) to kick start using single spa real quick

**Comment by joeldenning** [comment]
You can get support for this by modifying the webpack config. I'm open to adding css modules to create-single-spa. Am less certain about sass, as it would result in all users of webpack-config-single-spa downloading sass when the majority don't use it.
