### ISSUE TITLE
Missleading question while generating single-spa parcel starter app

### ISSUE THREAD

**Issue by gehemont** [single-spa/create-single-spa#340]
Hi, 

I noticed that when I am running `create-single-spa --moduleType app-parcel` process asks me if I would like to use routing. According to your documentation parcels are not supporting routing. 

![image](https://user-images.githubusercontent.com/58068278/142631611-77ba9bda-ca0f-4158-895b-d69eeea9e5e5.png)

I think that this question should be excluded when `--moduleType app-parcel` is selected. 

Is that any reason it works this way or it a bug?

Best,

**Comment by joeldenning** [comment]
The routing question is coming from Angular CLI, not from create-single-spa. But parcels can also use routing, it's just you have to worry about a couple limitations with it.
