### ISSUE TITLE
Unable to resolve bare specifier '@ambevtech/wms-push-notification-react-client'

### ISSUE THREAD

**Issue by AlexandreAkao** [single-spa/create-single-spa#365]
Hello guys
I'm facing this error:
![image](https://user-images.githubusercontent.com/40917812/197611523-961ad8d3-3f2e-43b9-990a-5d8554bd03ed.png)

But `@ambevtech/wms-push-notification-react-client` is only used in one micro frontend, I don't wanna share it with other micro frontends.

I know that probably will solve if I add this `@ambevtech/wms-push-notification-react-client` on import-map, but it is a private dependency that requires authentication.

This is my import-map:
![image](https://user-images.githubusercontent.com/40917812/197617357-36a7eb50-af4d-4960-bef4-d1f6db9c08fb.png)

Does anyone know how to solve this?

Thanks for the help :)

**Comment by filoxo** [comment]
Our webpack configs [use the orgName as a scope to define webpack `external`s](https://github.com/single-spa/create-single-spa/blob/main/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L116). Per the [create-single-spa documentation](https://single-spa.js.org/docs/create-single-spa/#usage),

> This changes whether package names that start with @your-org-name are treated as webpack externals or not. Defaults to true.

Set `orgPackagesAsExternal: false` in the singleSpaDefaults config and then either

- Enumerate which packages to mark as external
- Provide a function that does this and then merge that with single-spa's config

**Comment by AlexandreAkao** [comment]
When I set `orgPackagesAsExternal: false` shows a new error:
![image](https://user-images.githubusercontent.com/40917812/197620460-f4012586-2861-4a46-91d8-840c73a9ce22.png)

This is my webpack:
![image](https://user-images.githubusercontent.com/40917812/197620629-ccc4aeb2-5963-4c07-a137-81487d38cf3a.png)

**Comment by filoxo** [comment]
`process.env` is only compatible with Node but your code is making use of it. You need to compile it away, see webpack's [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/#usage) or [DefinePlugin](https://webpack.js.org/plugins/define-plugin/). 

These configs are intended to be a starting point. Not a one-size-fits-all solution like CRA or similar so keep that in mind.

**Comment by filoxo** [comment]
Seems like this could have also been caused by your use of streamBrowserify https://stackoverflow.com/questions/68542553/webpack-5process-is-not-defined-triggered-by-stream-browserify

**Comment by AlexandreAkao** [comment]
Setting the *ProvidePlugin* on Webpack.config the `process.env` shows, but with no values
```
plugins: [
  new webpack.ProvidePlugin({
    process: 'process/browser',
  }),
]
```

I'm migrating from a CRA project, so will be perfect if the envs be similar in the CRA, with all presets envs that CRA provides

**Comment by filoxo** [comment]
We intentionally don't provide a full replacement for CRA. It may also be a good idea to compare [CRA's webpack config](https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/config/webpack.config.js) with [our basic webpack config](https://github.com/single-spa/create-single-spa/blob/main/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js) so that you can enable the missing features yourself. See our FAQ here for some basic info and potential alternatives: https://single-spa.js.org/docs/faq/#create-react-app We unfortunately don't have the resources to do this on behalf of every user who wants to migrate.

**Comment by AlexandreAkao** [comment]
Okay fine, thanks a lot for the support 😊

**Comment by AlexandreAkao** [comment]
Only for information I found this plugin and work perfectly for environment variables https://github.com/mrsteele/dotenv-webpack
