### ISSUE TITLE
Create a single type for import module

### ISSUE THREAD

**Issue by AlexandreAkao** [single-spa/create-single-spa#366]
Hello guys
I want to create a single typing file for _Cross microfrontend imports_, preferably in the same project of functions/components/logic/etc

I have this 3 projects 
![image](https://user-images.githubusercontent.com/40917812/198893249-33b8669f-301d-4bad-ba33-fa21cb193880.png)

And I created a function on the `common project`
```ts
export function isEven(num: number) {
  return num % 2 === 0;
}
```

On the `pages project` I have this call
![image](https://user-images.githubusercontent.com/40917812/198893329-9574c0be-ecf2-4a8b-b0f2-de768d0b544f.png)

So I created this on `declarations.d.ts` file
```ts
declare module "@single-mfe/common" {
  const isEven: (number: number) => boolean;
}
```

And the error was resolved, but I wanna know if is possible, do this be automatic or only created one file global

**Comment by filoxo** [comment]
This is possible but outside of the scope of single-spa's responsibilities. I'd recommend you take a look at [rollup-plugin-dts](https://www.npmjs.com/package/rollup-plugin-dts) for emitting those declarations files, and sharing them can be as simple as publishing to npm or as complicated as something custom/innovative.
