### ISSUE TITLE
upgrade to babel-eslint@next

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#37]

**Comment by joeldenning** [comment]
Also, we need to specify that babel-eslint is the parser in the following files:

- https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/react/templates/.eslintrc
- https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/root-config/templates/.eslintrc
- https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/util-module/templates/.eslintrc

**Comment by TheMcMurder** [comment]
> Also, we need to specify that babel-eslint is the eslint parser in the following files:
> 
>     * https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/react/templates/.eslintrc
> 
>     * https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/root-config/templates/.eslintrc
> 
>     * https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/util-module/templates/.eslintrc

These files already seem to have `"parser": "babel-eslint"`

**Comment by joeldenning** [comment]
Oh then how did react-microfrontends not have it in its eslintrc??? Maybe it used an old version of create-single-spa?

**Comment by joeldenning** [comment]
This is resolved
