### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#38]
We should support typescript. I think easiest way might be to pass in an option to webpack-config-single-spa and webpack-config-single-spa-react:

```js
const webpackMerge = require("webpack-merge");
const singleSpaDefaults = require("webpack-config-single-spa-react");

module.exports = (webpackConfigEnv, webpackArgs) => {
  const defaultConfig = singleSpaDefaults({
    orgName: "org",
    projectName: "project",
    webpackConfigEnv,
    compiler: "babel|typescript",
    typecheck: "typescript|null",
  });

  return webpackMerge.smart(defaultConfig, {
    // modify the webpack config however you'd like to by adding to this object
  });
};
```

`compiler` would determine whether to use babel-loader or ts-loader for compilation. `typecheck` would determine whether to use [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin) or not.

**Comment by joeldenning** [comment]
https://github.com/openmrs is interested in using this. @brandones is leading the effort for them on this.

Here's an example of their tsconfig files: https://github.com/openmrs/openmrs-esm-api/blob/master/tsconfig.json

**Comment by brandones** [comment]
Thanks for the tag, @joeldenning ! Working on this this weekend.

**Comment by joeldenning** [comment]
@Sauloxd have you started working on this, yet? I know we had talked about it - would be a shame if both you and @brandones worked on it at the same time.

**Comment by brandones** [comment]
Oh okay, I'll hold off till we hear from them...

**Comment by joeldenning** [comment]
I don't think he's started on it - you should be fine to do so. I talked to him a few days ago about it as something he could help out with if he wanted to, but I don't think he's started.

**Comment by brandones** [comment]
Cool, I'm on it. Question --

> `compiler` would determine whether to use babel-loader or ts-loader for compilation.

Should we instead always use babel and add @babel/preset-typescript when generating a TS project?

**Comment by joeldenning** [comment]
> Should we instead always use babel and add @babel/preset-typescript when generating a TS project?

This might be easiest, but some people prefer using ts-loader instead of babel entirely. Let's start with things always using babel-loader and then provide option for ts-loader as needed.

**Comment by joeldenning** [comment]
This is published in https://github.com/single-spa/create-single-spa/releases/tag/v1.4.0
