### ISSUE TITLE
Support TypeScript 5+

### ISSUE THREAD

**Issue by seanmcquaid** [single-spa/create-single-spa#381]
Presently, it looks like TS 5 will break usage of this package.

**Comment by Taifunov** [comment]
Yeah, please update to have possibility to use TS 5+ version

**Comment by eckdanny** [comment]
```
pnpx create-single-spa@4.1.4 my-dir --skipInstall
cd my-dir
pnpm up typescript@5.x
pnpm build
```

builds fine so I don't think anything will be broken.

Are you simply asking for newly scaffolded project(s) generated by [`generator-single-spa`](https://www.npmjs.com/package/generator-single-spa) to use `typescript@5.x`?

**Comment by MilanKovacic** [comment]
single-spa supports modern typescript versions, including all module resolution algorthms: https://arethetypeswrong.github.io/?p=single-spa-react%406.0.1.
