### ISSUE TITLE
Does Single Spa support ExtJS framework?

### ISSUE THREAD

**Issue by kmprakashbabu** [single-spa/create-single-spa#391]
Hi, 
      I use Sencha's ExtJS for our front end. I am trying to see if I can use ExtJS in single spa micro frontend. But looks like there is no support for this. When I try to create a application/parcel it does not list ExtJS and when I chose  'Other" as framework, it asked me to raise a question/issue here. Please let me know if there is a plan to support ExtJS,

**Comment by MilanKovacic** [comment]
Hi, currently there is no official support for ExtJS. We aim to create, and maintain helpers for (most) popular frameworks. You can still create a lifecycle helper library yourself, following some of the examples listed here: https://single-spa.js.org/docs/ecosystem/.
