### ISSUE TITLE
Plugin for rsbuild or rspack for use with single-spa 🦀

### ISSUE THREAD

**Issue by douglaszaltron** [single-spa/create-single-spa#396]
In the past few weeks, I've been involved in and closely following the evolution of module federation and the recent possibility of exporting it via SDK. This has opened up the opportunity to use rspack and, consequently, [rsbuild](https://github.com/web-infra-dev/rsbuild), which can be compiled for both webpack and rspack.

It would be very interesting to develop a plugin for rsbuild, including the export of the application with single-spa. This would broaden the options available, allowing us to use not only webpack but also cra, vite, and rsbuild.

The implementation would follow the plugin format in rsbuild.

What do you think of the idea? @joeldenning

I believe that the single-spa community could help maintain the plugin, keeping it more developed and active.

There can be an rsbuild-plugin-single-spa, similar to https://github.com/WJSoftware/vite-plugin-single-spa

Hope that one day the community can implement and maintain such a plugin 😄

**Comment by MilanKovacic** [comment]
Hi, the current single-spa ecosystem is very large and requires a lot of maintenance. It is unlikely that we will be implementing support / templates / samples for rsbuild soon, as there are other items on the roadmap.
