### ISSUE TITLE
prettierignore and format script for root config

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#40]

**Comment by joeldenning** [comment]
`yarn format` would run `prettier --write './*'`. Prettierignore file would cover everything in root dir that prettier can't handle.

**Comment by filoxo** [comment]
Is this still an issue? I see that the root-config template has a [.prettierignore file](https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/root-config/templates/.prettierignore) already, and has a [script equivalent (`prettier`)](https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/root-config/templates/package.json#L6) for `format`.

**Comment by joeldenning** [comment]
I'd prefer switching from `prettier` to `format`, since naming it prettier makes it impossible to run custom prettier commands that are normally accessible via `yarn prettier`

**Comment by filoxo** [comment]
Thanks for clarifying! I hadn't quite understood the issue. That'll be a really small change.
