### ISSUE TITLE
Why is single-spa marked as external?

### ISSUE THREAD

**Issue by romulof** [single-spa/create-single-spa#407]
I'm not aware of all possible ways single-spa can be used, but in my use-case only my bootstrap uses single-spa package, yet `webpack-config-single-spa` marks it as external.

It would be better to bundle `single-spa` with it, avoiding the additional request.

**Comment by joeldenning** [comment]
`single-spa` is an external so that it is a shared dependency that can be reused across microfrontends. Only one instance of single-spa should be loaded on the web page.
