### ISSUE TITLE
Error copying missing .gitignore in generator-single-spa

### ISSUE THREAD

**Issue by andreaskc** [single-spa/create-single-spa#41]
```
npm init single-spa
? Select type to generate single-spa application / parcel
? Which framework do you want to use? react
? Which package manager do you want to use? npm
? Organization name (use lowercase and dashes) ls
? Project name (use lowercase and dashes) appbar
events.js:186
   throw er; // Unhandled 'error' event
   ^
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/andrewkallenbach/.npm/_npx/99955/lib/node_modules/create-single-spa/node_modules/generator-single-spa/src/react/templates/.gitignore
```

I've tried this on a Mac 10.14 and also a Windows 10 machine (and the Windows Ubuntu subsystem) with same result.
Create-single-spa is v 1.3.3
Node is 12.10

**Comment by joeldenning** [comment]
> Also, should we migrate this issue to the create-single-spa repo?

Yes, done.

> I've reproduced this locally

That's great to hear, I am unable to reproduce it for some reason.

> It appears that npm publish renames .gitignore to .npmignore

Good catch! Why then does unpkg show the gitignore inside of https://unpkg.com/browse/generator-single-spa@1.3.3/src/react/templates/.gitignore ?? The published code appears to have the gitignore - is it being removed during install??? Or is unpkg showing something that's not in the published tarball?

**Comment by joeldenning** [comment]
Note that the gitignores also show up in jsdelivr - https://cdn.jsdelivr.net/npm/generator-single-spa@1.3.3/src/react/templates/.gitignore

**Comment by filoxo** [comment]
Huh I wonder if its converted over while unpacking...

**Comment by TheMcMurder** [comment]
> Huh I wonder if its converted over while unpacking...

After investigation before submitting #71 @filoxo discovered that it's changed by NPM prior to publishing the module.

If I ran `npm pack` it would still be `.gitignore` but once you installed it globally (or used npx) from npm and looked at the code it would be `.npmignore`
