### ISSUE TITLE
Create-single-spa root-config is broken. 

### ISSUE THREAD

**Issue by sunilkolla** [single-spa/create-single-spa#418]
Create-single-spa root-config is broken with latest changes. EJS file is still old template.EMS changes broken npm start.

Is there a way I could use old version to create single-spa root and child?

**Comment by joeldenning** [comment]
Fix published in [create-single-spa@5.0.1](https://github.com/single-spa/create-single-spa/releases/tag/create-single-spa%405.0.1)

**Comment by Tomasgb97** [comment]
I'm sorry but I'm using create-single-spa 5.0.6 and im still having this issue that is supposed to be fixed @ version 5.0.1. Am I the only one?

**Comment by ahmedMshaban** [comment]
> I'm sorry but I'm using create-single-spa 5.0.6 and im still having this issue that is supposed to be fixed @ version 5.0.1. Am I the only one?

I have the same issue.

**Comment by joeldenning** [comment]
I verified that a root config using pnpm and npm are successfully generated and that `npm start` works without error, using create-single-spa@5.0.6. More details are needed to diagnose any issues - please open a new issues with more detailed explanation of the issue

**Comment by githubLewis** [comment]
I've raised a new issue for this here as I've hit the same error: https://github.com/single-spa/create-single-spa/issues/438
