### ISSUE TITLE
HookWebpackError: HMR is not implemented for module chunk format yet

### ISSUE THREAD

**Issue by juliogc** [single-spa/create-single-spa#425]
Hi, @joeldenning, it's me again! 😅 

I'm following up with the build I mentioned in the #421 issue, but now I get a new issue.
I recreated the whole stack using `create-single-spa@5.0.2` and everything went fine with the `single-spa` stack, but now I'm facing a new error mentioned in this issue title: `HookWebpackError: HMR is not implemented for module chunk format yet`

I understand that it's a webpack related issue but the docs don't make it clear how can I proceed with it and developing with HMR will be a pain 😕 

Should I get rid of the `single-spa/import-map-injector` and move to `SystemJS` or there is any workaround to keep working with the `libraryTarget: 'module'`?

**Comment by joeldenning** [comment]
See related https://github.com/webpack/webpack/issues/17636

**Comment by juliogc** [comment]
> Fix released in [webpack-config-single-spa@5.0.3](https://github.com/single-spa/create-single-spa/releases/tag/webpack-config-single-spa%405.0.3)

@joeldenning I appreciate the fix!

To clarify, if I want to keep HMR, should I continue using SystemJS?
Is there more information about the `outputSystemJS` flag? I found some info at [CHANGELOG#6.0.0](https://github.com/single-spa/create-single-spa/blob/main/packages/webpack-config-single-spa/CHANGELOG.md#600) but I would like to understand more about the effects of using it

**Comment by joeldenning** [comment]
> To clarify, if I want to keep HMR, should I continue using SystemJS?

Until webpack supports HMR for esm, yes

> Is there more information about the outputSystemJS flag? I found some info at [CHANGELOG#6.0.0](https://github.com/single-spa/create-single-spa/blob/main/packages/webpack-config-single-spa/CHANGELOG.md#600) but I would like to understand more about the effects of using it

See https://github.com/single-spa/create-single-spa/blob/0278cdcb66da11241e2dcbcd71ec27ae000de977/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L50 and https://github.com/single-spa/create-single-spa/issues/433
