### ISSUE TITLE
Vue and Angular create a new directory but React doesn't

### ISSUE THREAD

**Issue by TheMcMurder** [single-spa/create-single-spa#56]
More of a consistency issue than an actual bug.

Right now the CLI leverages vue-cli and angular-cli. Both of those CLIs create a new folder for you. 

Our react option does not.

Do we want to create a directory to be consistent across the possible choices?

If we do then I'll submit a PR

**Comment by joeldenning** [comment]
I think it should be an option - vue cli allows for creating in current directory with `vue create .`

https://github.com/vuejs/vue-cli/issues/1509

Don't think angular allows for it yet.

**Comment by TheMcMurder** [comment]
Does our CLI allow you to proxy to `vue create .` or do we always force a new directory?

**Comment by filoxo** [comment]
I think I'd prefer to emulate those other CLIs. Pass through a directory name where the files are put, and allow for `.` to create in current dir (where possible). Just my preference though.

**Comment by joeldenning** [comment]
> Does our CLI allow you to proxy to vue create . or do we always force a new directory?

create-single-spa always puts a react application in current directory, currently

> I think I'd prefer to emulate those other CLIs. Pass through a directory name where the files are put, and allow for . to create in current dir (where possible). Just my preference though.

I agree
