### ISSUE TITLE
Switch to single-spa-react-ts-config npm package

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#60]
See related https://github.com/single-spa/create-single-spa/pull/51#discussion_r405589124

**Comment by joeldenning** [comment]
cc @brandones

**Comment by brandones** [comment]
Can one extend a JSON config?

**Comment by joeldenning** [comment]
Yes, see https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends

**Comment by joeldenning** [comment]
I think the tsconfig would change to be just this:

```json
{
  "extends": "single-spa-react-ts-config"
}
```

**Comment by joeldenning** [comment]
done

**Comment by joeldenning** [comment]
Actually wait, this isn't done

**Comment by joeldenning** [comment]
Also I think this ts config should not be react-specific - should be very easy to add jsx: react to the react generator’s tsconfig template

**Comment by joeldenning** [comment]
Released in 1.7.0
