### ISSUE TITLE
When choosing typescript, npm/yarn install occurs twice

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#61]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/5524384/78800665-f021ba00-7978-11ea-9e5f-d4472898420c.png">

See https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/react/generator-single-spa-react.js#L159 and https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/react/generator-single-spa-react.js#L163. Also see https://github.com/single-spa/create-single-spa/pull/51#discussion_r404885125

cc @brandones

**Comment by brandones** [comment]
Whoops, I'm sure I saw that output and it just didn't register. But this would seem to contradict the Yeoman docs, which (as I pointed out in #51 ) say

> Yeoman will ensure the npm install command is only run once even if it is called multiple times by multiple generators. (https://yeoman.io/authoring/dependencies.html)

I reckon a bug should be filed against [yeoman/yo](https://github.com/yeoman/yo/issues)?

**Comment by joeldenning** [comment]
Yeah it seems like yeoman's documentation is either incorrect or there is a bug with yo. Want to open the issue?

**Comment by brandones** [comment]
Sure, will do
