### ISSUE TITLE
Invalid root config URL in importmap

### ISSUE THREAD

**Issue by terry-hoekstra** [single-spa/create-single-spa#89]
When generating the root-config application the root-config.js file is prepended with the company name, but the URL in the import map points to //localhost:9000/root-config.js and will cause an unable to load module error in systemjs.

Currently generated importmap:
`      "imports": {
        "@company/root-config": "//localhost:9000/root-config.js"
      }`

Expected generated importmap:
`      "imports": {
        "@company/root-config": "//localhost:9000/company-root-config.js"
      }`

**Comment by joeldenning** [comment]
Thanks for the clear bug report, this has been fixed and is released in https://github.com/single-spa/create-single-spa/releases/tag/v1.5.3
