### ISSUE TITLE
Crash when creating vue application (since 1.5.2)

### ISSUE THREAD

**Issue by cylewitruk** [single-spa/create-single-spa#91]
When running `create-single-spa` and choosing `vue`, I'm seeing a crash since v1.5.2 with a **global installation** of `vue-cli` (guessing this is related to the fix implemented #19 for the similar problem described in #18):

**The error:**

*Note: Error also presents when passing `--framework vue` instead of choosing framework via the prompts.*

```bash
$ create-single-spa
? Directory for new project .
? Select type to generate single-spa application / parcel
? Which framework do you want to use? vue
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: spawn vue ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn vue',
  path: 'vue',
  spawnargs: [ 'create', '.' ]
}
```

**CLI Versions:**

*Vue CLI (globally installed):*

```bash
$ vue --version
@vue/cli 4.3.1
```

*create-single-spa (globally installed):*

```bash
$ create-single-spa --version
1.5.3
```

**Comment by joeldenning** [comment]
Hmm I just tried this with a global installation of vue and it worked. I am on OSX - are you perhaps on Windows? We might need to change the command to `vue.cmd`

**Comment by joeldenning** [comment]
I confirmed on a windows machine that the problem is the lack of `.cmd` on the commands that are spawned. Will submit a fix.

**Comment by joeldenning** [comment]
This is fixed in https://github.com/single-spa/create-single-spa/releases/tag/v1.5.4

**Comment by cylewitruk** [comment]
Sorry, yeah it was on windows as you found out, I should have included that.  

Confirmed fixed, thanks for the quick response :)
