### ISSUE TITLE
Add root config prompt for Zone.js

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#95]
We should ask the user if they're using Angular and then inject a script to load zonejs into the index.ejs file if so. From what I've seen, it's best just to put it right into the html file instead of the import map because it has to be loaded before you download `@angular/core`

**Comment by joeldenning** [comment]
Related - https://single-spa.slack.com/archives/CGETM8T5X/p1589409372299800

**Comment by filoxo** [comment]
I think the implementation of this should add a commented-out zone.js script in the index.ejs template. My reasoning is as follows: 

- Prompting is a lot more work
- A beginner may not know whether they can or need to support Angular at the time they create a root config
- Its easy to enable even after the config has been created vs hiding it away unless you included it when prompted to

[The coexisting angular microfrontends index.html](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/c5442b672b567eae8d8ac51e159e48d3ceb7fc04/root-html-file/index.html#L22) is an example of how it should be included in the [root-config template index page](https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/root-config/templates/src/index.ejs).

**Comment by joeldenning** [comment]
Sounds good
